matrix:
- name: markdown
  hunspell:  # I am unsure if this is necessary, but if we ever want to use a custom dict, this is how to do it.
    d: en_US
  aspell:
    lang: en
    d: en_US  # Same as above.
    mode:
      - markdown
      - url
      - email
    ignore-case: true  # This is definitely working. Add capitalised words only for proper nouns, etc., to spelling_wordlist.
    ignore-accents: true  # Uncertain what this is doing, but leaving it in.
  dictionary:
    wordlists:
    - docs/spelling_wordlist
    output: _build/dictionary/python.dic
  sources:
  - 'docs/**/*.md'
  - README.md
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.toc
      - markdown.extensions.admonition
      - markdown.extensions.attr_list
      - pymdownx.superfences
      - pymdownx.blocks.admonition
      - pymdownx.blocks.caption
      - pymdownx.blocks.tab
      - pymdownx.details
  - pyspelling.filters.html:
      comments: false
      attributes:
        - title
        - alt
      ignores:
        - 'code'
        - 'pre'
        - 'div'
        - 'nospell'
        - 'script'
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # Ignore the Jinja directives
        - open: '{% '
          close: ' %}'
        # Ignores the autorefs link targets
        - open: '\]\['
          close: '\]'
        # Ignore the single line Snippets syntax
        - open: '-8<- '
          close: '$'
        # Ignore the .md URLs - appears to be fixed by mode: url above, leaving in place for now
        #- open: 'https?:'
        #  close: '\.md(:[-\w]+)?'
        # Ignore urls in frontmatter - This is still necessary with mode: url
        - open: 'url: '
          close: '$'
        # Ignore toc in frontmatter
        - open: '- toc'
          close: '$'
        # Ignore numbers with a suffix, e.g. dates
        - open: '[0-9]+'
          close: '[rshndt]*'
        # Ignore version numbers
        - open: '[0-9\.]+[a-z]*'
          close: '[0-9]*'
